openapi: 3.1.0
info:
  title: Library API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local dev servers
  - url: https://library-api-88rw.onrender.com
    description: Production server on render
tags:
  - name: User
    description: User-related endpoints
  - name: Author
    description: Author-related endpoints
  - name: Book
    description: Book-related endpoints
  - name: Review
    description: Review-related endpoints
paths:
  /users:
    get:
      summary: List all users
      tags:
        - User
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./components/schemas/users.yaml
        '403':
          $ref: ./components/responses/ForbiddenRequest.yaml
        '401':
          $ref: ./components/responses/UnauthorizedRequest.yaml
  /users/signup:
    post:
      summary: User sign up
      tags:
       - User
      requestBody:
        description: Info to get signed up
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: TameImpala
                password:
                  type: string
                  example: didyouknowtameimpalaisoneguy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                    example: 3
                  username:
                    type: string
                    example: TameImpala
                  role: 
                    type: string
                    example: member
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: Username must be alphanumeric
        '409':
          description: Username not unique
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: Username must unique
        '403':
          $ref: ./components/responses/ForbiddenRequest.yaml
        '401':
          $ref: ./components/responses/UnauthorizedRequest.yaml
  /users/login:
    post:
      summary: User login
      tags:
       - User
      requestBody:
        description: Info to login
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: TameImpala
                password:
                  type: string
                  example: didyouknowtameimpalaisoneguy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
        '401':
          description: Validation failed, login failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: Invalid Credentials
  /users/{id}:
    put:
      summary: Update a users name and password via their user_id
      tags: 
      - User
      parameters:
        - name: id
          in: path
          description: user_id
          required: true
          schema:
            type: integer
            example: 3
      requestBody:
        description: Info to change
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: BonJovi
                password:
                  type: string
                  example: BrandNewPassword
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                    example: 3
                  username:
                    type: string
                    example: BonJovi
                  role:
                    type: string
                    example: member                  
        '404':
          description: User Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: Could not find a user with that id
        '409':
          description: Username not unique
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: Username must unique
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: Password mut be between 8 and 64 characters
        '403':
          $ref: ./components/responses/ForbiddenRequest.yaml
        '401':
          $ref: ./components/responses/UnauthorizedRequest.yaml
    delete:
      summary: Delete a user
      parameters:
        - name: id
          in: path
          description: user_id
          required: true
          schema:
            type: integer
            example: 3
      responses:
        '204':
          description: OK
        '404':
          description: User not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: Could not find a user with that id
        '403':
          $ref: ./components/responses/ForbiddenRequest.yaml
        '401':
          $ref: ./components/responses/UnauthorizedRequest.yaml
        
      
  /users/{id}/role:
    patch:
      summary: Update a users role
      tags:
        - User
      parameters:
        - name: id
          in: path
          description: user_id
          required: true
          schema:
            type: integer
            example: 3
      requestBody:
        description: Role to update
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string 
                  enum: [member, admin]
                  example: admin
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                    example: 3
                  username:
                    type: string
                    example: BonJovi
                  role:
                    type: string
                    enum: [memeber, admin]
                    example: admin
        '404':
          description: User not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: Could not find a user with that id
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: Role must be memeber or admin
        '403':
          $ref: ./components/responses/ForbiddenRequest.yaml
        '401':
          $ref: ./components/responses/UnauthorizedRequest.yaml
  