openapi: 3.1.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
info:
  title: Library API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local dev servers
  - url: https://library-api-88rw.onrender.com
    description: Production server on render
tags:
  - name: User
    description: User-related endpoints
  - name: Author
    description: Author-related endpoints
  - name: Book
    description: Book-related endpoints
  - name: Review
    description: Review-related endpoints
paths:
  /libapi/users:
    $ref: paths/users.yaml
  /libapi/users/signup:
    $ref: paths/users_signup.yaml
  /libapi/users/login:
    $ref: paths/users_login.yaml
  /libapi/users/{id}:
    $ref: paths/users_{id}.yaml
  /libapi/users/{id}/role:
    $ref: paths/users_{id}_role.yaml
  /libapi/authors:
    $ref: paths/authors.yaml
  /libapi/authors/{id}: 
    $ref: paths/authors_{id}.yaml
  /libapi/books:
    $ref: paths/books.yaml
  /libapi/books/{id}: 
    $ref: paths/books_{id}.yaml
  /libapi/reviews:
    $ref: paths/reviews.yaml
  /libapi/reviews/{id}: 
    $ref: paths/reviews_{id}.yaml